version: "3.9"

services:
    # RABBIT_HOSTNAME=rabbit
    rabbit: 
        build:
            dockerfile: ./rabbit/Dockerfile
        ports:
            - 9090:15672
            - 5672:5672
        environment:
            RABBITMQ_DEFAULT_USER: "rabbit"
            RABBITMQ_DEFAULT_PASS: "password"
            RABBITMQ_CONFIG_FILE: "/opt/rabbitmq/etc/rabbitmq/rabbitmq.conf"
        volumes:
            - ./rabbit/definitions.json:/opt/rabbitmq/etc/rabbitmq/definitions.json
            - ./rabbit/rabbitmq.conf:/opt/rabbitmq/etc/rabbitmq/rabbitmq.conf
            - ./rabbit/data/:/var/lib/rabbitmq/
            - ./rabbit/logs/:/var/log/rabbitmq/
    client:
        image: nginx:1-alpine3.18-slim
        ports:
            - 8080:80
        volumes:
            - ./client/build/:/usr/share/nginx/html/
    M1:
        # depends_on: 
        #     rabbit:
        #         condition: service_started
        image: node:18.17.1-alpine3.18
        ports:
            - 9091:9091
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
            - SERVICE_NAME=M1
            - SERVICE_PORT=9091
            - RABBIT_USER=requester
            - RABBIT_PASSWORD=password
            - RABBIT_PORT=5672
            - RABBIT_HOSTNAME=rabbit
            - RABBIT_VHOST=/myvhost
            - RABBIT_EXCHANGE=messaging_exchange
            - RABBIT_REQKEY=requests_key
            - RABBIT_READQUEUE=tasks_queue
        volumes:
            - ./micro1/:/home/node/app
            - ./node_modules/:/home/node/app/node_modules/
        command: "npm run start"
    M2:
        # depends_on: 
        #     rabbit:
        #         condition: service_started
        image: node:18.17.1-alpine3.18
        ports:
            - 9092:9092
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
            - SERVICE_NAME=M2
            - SERVICE_PORT=9092
            - RABBIT_USER=tasker
            - RABBIT_PASSWORD=password
            - RABBIT_PORT=5672
            - RABBIT_HOSTNAME=rabbit
            - RABBIT_VHOST=/myvhost
            - RABBIT_EXCHANGE=messaging_exchange
            - RABBIT_READQUEUE=requests_queue
        volumes:
            - ./micro2/:/home/node/app
            - ./node_modules/:/home/node/app/node_modules/
        command: "npm run start"

networks:
    default:
        driver: bridge
